export const mockEvents = [
  {
    id: '1',
    title: 'Summer Music Festival 2025',
    description: 'Join us for an unforgettable night of live music featuring top artists from around the world. Experience amazing performances across multiple stages.',
    category: 'music',
    price: 75,
    date: '2025-07-15T18:00:00',
    location: 'Central Park, New York',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Tech Innovation Summit',
    description: 'Discover the latest in technology and innovation. Network with industry leaders and explore cutting-edge solutions.',
    category: 'tech',
    price: 120,
    date: '2025-08-22T09:00:00',
    location: 'Convention Center, San Francisco',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Food & Wine Gala',
    description: 'An exquisite evening celebrating culinary excellence. Taste dishes from renowned chefs and sample premium wines.',
    category: 'food',
    price: 95,
    date: '2025-09-10T19:00:00',
    location: 'Grand Hotel, Chicago',
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Championship Finals',
    description: 'Witness history as the best teams compete for the championship title. Don\'t miss this epic showdown!',
    category: 'sports',
    price: 150,
    date: '2025-06-30T20:00:00',
    location: 'Stadium Arena, Los Angeles',
    image_url: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Modern Art Exhibition',
    description: 'Explore contemporary masterpieces from emerging and established artists. A journey through modern creativity.',
    category: 'arts',
    price: 25,
    date: '2025-07-05T10:00:00',
    location: 'Metropolitan Museum, New York',
    image_url: 'https://images.unsplash.com/photo-1514905552197-0610a4d8fd73?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Digital Marketing Workshop',
    description: 'Learn proven strategies to grow your business online. Hands-on workshop with industry experts.',
    category: 'workshop',
    price: 45,
    date: '2025-08-15T14:00:00',
    location: 'Business Hub, Boston',
    image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Jazz Night Under the Stars',
    description: 'Enjoy smooth jazz melodies in an intimate outdoor setting. Perfect evening for music lovers.',
    category: 'music',
    price: 50,
    date: '2025-07-20T20:30:00',
    location: 'Rooftop Terrace, Miami',
    image_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Marathon City Run',
    description: 'Challenge yourself in our annual city marathon. All fitness levels welcome!',
    category: 'sports',
    price: 30,
    date: '2025-09-05T07:00:00',
    location: 'Downtown, Seattle',
    image_url: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=600&fit=crop',
    created_at: new Date().toISOString(),
  },
];
